#+BEGIN_QUOTE
A LISP programmer knows the value of everything, but the cost of nothing.

--- Alan Perlis
#+END_QUOTE

This library is a toolbox for measuring the run time of Common Lisp code.
It provides macros and functions for accurate benchmarking and lightweight
monitoring.  Furthermore, it provides predefined benchmarks to determine
the cost of certain actions on a given platform and implementation.

I hope you find it useful. If you have new ideas for benchmarks, or
suggestions on how to improve existing ones, feel free to contact me.

** Usage
To run all predefined benchmarks, simply execute

#+BEGIN_SRC lisp :results output
(asdf:test-system :the-cost-of-nothing)
#+END_SRC

To obtain the execution time of an expression as a double-float in seconds,
execute
#+BEGIN_SRC lisp
(benchmark EXPRESSION)
#+END_SRC

To have said execution time immediately and human-readably written to
*trace-output* (much like CL:TIME), use
#+BEGIN_SRC lisp
(bench EXPRESSION)
#+END_SRC

** Implementation
A statement like
#+BEGIN_SRC lisp
(benchmark
 (loop for key across keys do
   (benchmark (gethash key table))))
#+END_SRC

is a macro that expands into something like
#+BEGIN_SRC lisp
(benchmark-thunk
 (lambda (#:iterations723)
   (loop :repeat #:iterations723
         :do (loop for key across keys
                   do (touch (gethash key table))))))
#+END_SRC

The function TOUCH is explicitly declared notinline, to prevent compiler
optimization. The function BENCHMARK-THUNK invokes its argument repeatedly
and with various numbers of iterations to determine an accurate result.

** Remember

#+BEGIN_QUOTE
There are lies, damned lies, and benchmarks.
#+END_QUOTE
