#+BEGIN_QUOTE
A LISP programmer knows the value of everything, but the cost of nothing.

--- Alan Perlis
#+END_QUOTE

This library is a toolbox for measuring the run time of Common Lisp code.
It provides macros and functions for accurate benchmarking and lightweight
monitoring.  Furthermore, it provides predefined benchmarks to determine
the cost of certain actions on a given platform and implementation.

I hope you find it useful. If you have new ideas for benchmarks, or
suggestions on how to improve existing ones, feel free to contact me.

** Benchmarking
To run all predefined benchmarks, simply execute

#+BEGIN_SRC lisp :results output
(asdf:test-system :the-cost-of-nothing)
#+END_SRC

To obtain the execution time of an expression as a double-float in seconds,
execute
#+BEGIN_SRC lisp
(benchmark EXPRESSION)
#+END_SRC

To have said execution time immediately and human-readably written to
*trace-output* (much like CL:TIME), execute
#+BEGIN_SRC lisp
(bench EXPRESSION)
#+END_SRC

** Monitoring

Coming soon.

** Remember

#+BEGIN_QUOTE
There are lies, damned lies, and benchmarks.
#+END_QUOTE
